project:
  type: website
  resources:
    - cv.pdf

website:
  title: "TIERNAN"
  description: "The personal website of Tiernan Martin"
  site-url: https://tiernanmartin.com
  favicon: profile.png
  navbar:
    right:
      - text: About
        href: index.qmd
      - text: Talks
        href: talks.qmd
      - text: Projects
        href: projects.qmd
  page-footer: 
    center: "© Copyright 2024 Tiernan Martin."

format:
  html:
    theme: united
    css: styles.css
    toc: true

editor: visual

