project:
  type: website
  resources:
    - cv.pdf

website:
  title: "Tiernan Martin"
  description: "The personal website of Tiernan Martin"
  site-url: https://tiernanmartin.com
  favicon: profile.png
  navbar:
    right:
      - text: About
        href: index.qmd
      - text: Talks
        href: talks.qmd
      - text: Projects
        href: projects.qmd
  page-footer:
    left: "© Copyright 2024 Tiernan Martin. Except where otherwise noted, all text and images licensed CC-BY-NC 4.0."

format:
  html:
    theme: united
    css: styles.css
    toc: true

editor: visual

